apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
        - name: content-service
          image: hmsmiraz/techedu-content-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: MYSQL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: app-password
            - name: DATABASE_URL
              value: mysql+pymysql://techedu:$(MYSQL_APP_PASSWORD)@mysql:3306/content_db
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: cors-origins
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://observability-agent.observability:4318"
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
spec:
  type: ClusterIP
  selector:
    app: content-service
  ports:
    - port: 8001
      targetPort: 8001
