apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql-configmap.yaml
  - mysql-statefulset.yaml
  - auth-service.yaml
  - content-service.yaml
  - gateway.yaml
  - landing.yaml
  - admin.yaml
  - learning-portal.yaml
