apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learning-portal
  template:
    metadata:
      labels:
        app: learning-portal
    spec:
      containers:
        - name: learning-portal
          image: hmsmiraz/techedu-learning-portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: learning-portal
spec:
  type: ClusterIP
  selector:
    app: learning-portal
  ports:
    - port: 3002
      targetPort: 3002
